import java.io.PrintStream;
import java.util.Scanner;
public class test_project{
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        String a=input.next();
         if(a.length() <=8){
            System.out.println("密码长度必须大于8位！");}
        else{System.out.println("密码设置成功！");}
        
    }
}







//this is a testing project for my java learning, it is for testing.